* ENCODING=ISO-8859-1
NAME          IloCplex
ROWS
 N  obj     
 E  c1      
 E  c2      
 E  c3      
 E  c4      
 E  c5      
 E  c6      
 E  c7      
 E  c8      
 E  c9      
 E  c10     
 E  c11     
 E  c12     
 E  c13     
 E  c14     
 E  c15     
 E  c16     
 E  c17     
 E  c18     
 E  c19     
 E  c20     
 E  c21     
 E  c22     
 E  c23     
 E  c24     
 E  c25     
 E  c26     
 E  c27     
 E  c28     
 E  c29     
 E  c30     
 E  c31     
 E  c32     
 E  c33     
 E  c34     
 E  c35     
 E  c36     
 E  c37     
COLUMNS
    MARK0000  'MARKER'                 'INTORG'
    x1        c1                              1
    x1        c12                            -1
    x1        c13                            -1
    x1        c14                            -1
    x1        c15                            -1
    x1        c16                             1
    x1        c17                             1
    x1        c18                             1
    x1        c19                             1
    x1        c20                             1
    x1        c21                             1
    x1        c22                            -1
    x1        c23                            -1
    x1        c24                            -1
    x1        c25                            -1
    x1        c26                            -1
    x1        c27                            -1
    x1        c28                            -1
    x1        c29                            -1
    x1        c30                            -1
    x1        c31                            -1
    x1        c32                            -1
    x1        c33                            -1
    x1        c34                            -1
    x1        c35                            -1
    x1        c36                            -1
    x1        c37                            -1
    x2        c1                              1
    x2        c5                              1
    x2        c8                              1
    x2        c10                             1
    x2        c11                             1
    x2        c12                            -1
    x2        c13                            -1
    x2        c14                            -1
    x2        c16                             1
    x2        c17                             1
    x2        c19                             1
    x2        c22                            -1
    x2        c23                            -1
    x2        c25                            -1
    x2        c26                            -1
    x2        c28                            -1
    x2        c31                            -1
    x2        c33                            -1
    x3        c1                              1
    x3        c12                            -1
    x3        c13                            -1
    x3        c14                            -1
    x3        c15                             1
    x3        c16                             1
    x3        c17                             1
    x3        c18                            -1
    x3        c19                             1
    x3        c20                            -1
    x3        c21                            -1
    x3        c22                            -1
    x3        c23                            -1
    x3        c24                             1
    x3        c25                            -1
    x3        c26                            -1
    x3        c27                             1
    x3        c28                            -1
    x3        c29                             1
    x3        c30                            -1
    x3        c31                            -1
    x3        c32                             1
    x3        c33                            -1
    x3        c34                             1
    x3        c35                            -1
    x3        c36                             1
    x3        c37                            -1
    x4        c1                              1
    x4        c4                              1
    x4        c7                              1
    x4        c9                              1
    x4        c11                             1
    x4        c12                            -1
    x4        c13                            -1
    x4        c15                            -1
    x4        c16                             1
    x4        c18                             1
    x4        c20                             1
    x4        c22                            -1
    x4        c24                            -1
    x4        c25                            -1
    x4        c27                            -1
    x4        c30                            -1
    x4        c32                            -1
    x4        c35                            -1
    x5        c1                              1
    x5        c4                              1
    x5        c5                              1
    x5        c7                              1
    x5        c8                              1
    x5        c9                              1
    x5        c10                             1
    x5        c11                             1
    x5        c12                            -1
    x5        c13                            -1
    x5        c16                             1
    x5        c22                            -1
    x5        c25                            -1
    x6        c1                              1
    x6        c4                              1
    x6        c7                              1
    x6        c9                              1
    x6        c11                             1
    x6        c12                            -1
    x6        c13                            -1
    x6        c15                             1
    x6        c16                             1
    x6        c18                            -1
    x6        c20                            -1
    x6        c22                            -1
    x6        c24                             1
    x6        c25                            -1
    x6        c27                             1
    x6        c30                            -1
    x6        c32                             1
    x6        c35                            -1
    x7        c1                              1
    x7        c12                            -1
    x7        c13                            -1
    x7        c14                             1
    x7        c15                            -1
    x7        c16                             1
    x7        c17                            -1
    x7        c18                             1
    x7        c19                            -1
    x7        c20                             1
    x7        c21                            -1
    x7        c22                            -1
    x7        c23                             1
    x7        c24                            -1
    x7        c25                            -1
    x7        c26                             1
    x7        c27                            -1
    x7        c28                            -1
    x7        c29                             1
    x7        c30                            -1
    x7        c31                             1
    x7        c32                            -1
    x7        c33                            -1
    x7        c34                             1
    x7        c35                            -1
    x7        c36                            -1
    x7        c37                             1
    x8        c1                              1
    x8        c5                              1
    x8        c8                              1
    x8        c10                             1
    x8        c11                             1
    x8        c12                            -1
    x8        c13                            -1
    x8        c14                             1
    x8        c16                             1
    x8        c17                            -1
    x8        c19                            -1
    x8        c22                            -1
    x8        c23                             1
    x8        c25                            -1
    x8        c26                             1
    x8        c28                            -1
    x8        c31                             1
    x8        c33                            -1
    x9        c1                              1
    x9        c12                            -1
    x9        c13                            -1
    x9        c14                             1
    x9        c15                             1
    x9        c16                             1
    x9        c17                            -1
    x9        c18                            -1
    x9        c19                            -1
    x9        c20                            -1
    x9        c21                             1
    x9        c22                            -1
    x9        c23                             1
    x9        c24                             1
    x9        c25                            -1
    x9        c26                             1
    x9        c27                             1
    x9        c28                            -1
    x9        c29                            -1
    x9        c30                            -1
    x9        c31                             1
    x9        c32                             1
    x9        c33                            -1
    x9        c34                            -1
    x9        c35                            -1
    x9        c36                             1
    x9        c37                             1
    x10       c1                              1
    x10       c3                              1
    x10       c6                              1
    x10       c9                              1
    x10       c10                             1
    x10       c12                            -1
    x10       c14                            -1
    x10       c15                            -1
    x10       c17                             1
    x10       c18                             1
    x10       c21                             1
    x10       c23                            -1
    x10       c24                            -1
    x10       c28                            -1
    x10       c29                            -1
    x10       c30                            -1
    x10       c36                            -1
    x10       c37                            -1
    x11       c1                              1
    x11       c3                              1
    x11       c5                              1
    x11       c6                              1
    x11       c8                              1
    x11       c9                              1
    x11       c10                             1
    x11       c11                             1
    x11       c12                            -1
    x11       c14                            -1
    x11       c17                             1
    x11       c23                            -1
    x11       c28                            -1
    x12       c1                              1
    x12       c3                              1
    x12       c6                              1
    x12       c9                              1
    x12       c10                             1
    x12       c12                            -1
    x12       c14                            -1
    x12       c15                             1
    x12       c17                             1
    x12       c18                            -1
    x12       c21                            -1
    x12       c23                            -1
    x12       c24                             1
    x12       c28                            -1
    x12       c29                             1
    x12       c30                            -1
    x12       c36                             1
    x12       c37                            -1
    x13       c1                              1
    x13       c3                              1
    x13       c4                              1
    x13       c6                              1
    x13       c7                              1
    x13       c9                              1
    x13       c10                             1
    x13       c11                             1
    x13       c12                            -1
    x13       c15                            -1
    x13       c18                             1
    x13       c24                            -1
    x13       c30                            -1
    x14       c1                              1
    x14       c3                              1
    x14       c4                              1
    x14       c5                              1
    x14       c6                              1
    x14       c7                              1
    x14       c8                              1
    x14       c9                              1
    x14       c10                             1
    x14       c11                             1
    x14       c12                            -1
    x15       c1                              1
    x15       c3                              1
    x15       c4                              1
    x15       c6                              1
    x15       c7                              1
    x15       c9                              1
    x15       c10                             1
    x15       c11                             1
    x15       c12                            -1
    x15       c15                             1
    x15       c18                            -1
    x15       c24                             1
    x15       c30                            -1
    x16       c1                              1
    x16       c3                              1
    x16       c6                              1
    x16       c9                              1
    x16       c10                             1
    x16       c12                            -1
    x16       c14                             1
    x16       c15                            -1
    x16       c17                            -1
    x16       c18                             1
    x16       c21                            -1
    x16       c23                             1
    x16       c24                            -1
    x16       c28                            -1
    x16       c29                             1
    x16       c30                            -1
    x16       c36                            -1
    x16       c37                             1
    x17       c1                              1
    x17       c3                              1
    x17       c5                              1
    x17       c6                              1
    x17       c8                              1
    x17       c9                              1
    x17       c10                             1
    x17       c11                             1
    x17       c12                            -1
    x17       c14                             1
    x17       c17                            -1
    x17       c23                             1
    x17       c28                            -1
    x18       c1                              1
    x18       c3                              1
    x18       c6                              1
    x18       c9                              1
    x18       c10                             1
    x18       c12                            -1
    x18       c14                             1
    x18       c15                             1
    x18       c17                            -1
    x18       c18                            -1
    x18       c21                             1
    x18       c23                             1
    x18       c24                             1
    x18       c28                            -1
    x18       c29                            -1
    x18       c30                            -1
    x18       c36                             1
    x18       c37                             1
    x19       c1                              1
    x19       c12                            -1
    x19       c13                             1
    x19       c14                            -1
    x19       c15                            -1
    x19       c16                            -1
    x19       c17                             1
    x19       c18                             1
    x19       c19                            -1
    x19       c20                            -1
    x19       c21                             1
    x19       c22                             1
    x19       c23                            -1
    x19       c24                            -1
    x19       c25                            -1
    x19       c26                             1
    x19       c27                             1
    x19       c28                            -1
    x19       c29                            -1
    x19       c30                            -1
    x19       c31                            -1
    x19       c32                            -1
    x19       c33                             1
    x19       c34                             1
    x19       c35                             1
    x19       c36                            -1
    x19       c37                            -1
    x20       c1                              1
    x20       c5                              1
    x20       c8                              1
    x20       c10                             1
    x20       c11                             1
    x20       c12                            -1
    x20       c13                             1
    x20       c14                            -1
    x20       c16                            -1
    x20       c17                             1
    x20       c19                            -1
    x20       c22                             1
    x20       c23                            -1
    x20       c25                            -1
    x20       c26                             1
    x20       c28                            -1
    x20       c31                            -1
    x20       c33                             1
    x21       c1                              1
    x21       c12                            -1
    x21       c13                             1
    x21       c14                            -1
    x21       c15                             1
    x21       c16                            -1
    x21       c17                             1
    x21       c18                            -1
    x21       c19                            -1
    x21       c20                             1
    x21       c21                            -1
    x21       c22                             1
    x21       c23                            -1
    x21       c24                             1
    x21       c25                            -1
    x21       c26                             1
    x21       c27                            -1
    x21       c28                            -1
    x21       c29                             1
    x21       c30                            -1
    x21       c31                            -1
    x21       c32                             1
    x21       c33                             1
    x21       c34                            -1
    x21       c35                             1
    x21       c36                             1
    x21       c37                            -1
    x22       c1                              1
    x22       c4                              1
    x22       c7                              1
    x22       c9                              1
    x22       c11                             1
    x22       c12                            -1
    x22       c13                             1
    x22       c15                            -1
    x22       c16                            -1
    x22       c18                             1
    x22       c20                            -1
    x22       c22                             1
    x22       c24                            -1
    x22       c25                            -1
    x22       c27                             1
    x22       c30                            -1
    x22       c32                            -1
    x22       c35                             1
    x23       c1                              1
    x23       c4                              1
    x23       c5                              1
    x23       c7                              1
    x23       c8                              1
    x23       c9                              1
    x23       c10                             1
    x23       c11                             1
    x23       c12                            -1
    x23       c13                             1
    x23       c16                            -1
    x23       c22                             1
    x23       c25                            -1
    x24       c1                              1
    x24       c4                              1
    x24       c7                              1
    x24       c9                              1
    x24       c11                             1
    x24       c12                            -1
    x24       c13                             1
    x24       c15                             1
    x24       c16                            -1
    x24       c18                            -1
    x24       c20                             1
    x24       c22                             1
    x24       c24                             1
    x24       c25                            -1
    x24       c27                            -1
    x24       c30                            -1
    x24       c32                             1
    x24       c35                             1
    x25       c1                              1
    x25       c12                            -1
    x25       c13                             1
    x25       c14                             1
    x25       c15                            -1
    x25       c16                            -1
    x25       c17                            -1
    x25       c18                             1
    x25       c19                             1
    x25       c20                            -1
    x25       c21                            -1
    x25       c22                             1
    x25       c23                             1
    x25       c24                            -1
    x25       c25                            -1
    x25       c26                            -1
    x25       c27                             1
    x25       c28                            -1
    x25       c29                             1
    x25       c30                            -1
    x25       c31                             1
    x25       c32                            -1
    x25       c33                             1
    x25       c34                            -1
    x25       c35                             1
    x25       c36                            -1
    x25       c37                             1
    x26       c1                              1
    x26       c5                              1
    x26       c8                              1
    x26       c10                             1
    x26       c11                             1
    x26       c12                            -1
    x26       c13                             1
    x26       c14                             1
    x26       c16                            -1
    x26       c17                            -1
    x26       c19                             1
    x26       c22                             1
    x26       c23                             1
    x26       c25                            -1
    x26       c26                            -1
    x26       c28                            -1
    x26       c31                             1
    x26       c33                             1
    x27       c1                              1
    x27       c12                            -1
    x27       c13                             1
    x27       c14                             1
    x27       c15                             1
    x27       c16                            -1
    x27       c17                            -1
    x27       c18                            -1
    x27       c19                             1
    x27       c20                             1
    x27       c21                             1
    x27       c22                             1
    x27       c23                             1
    x27       c24                             1
    x27       c25                            -1
    x27       c26                            -1
    x27       c27                            -1
    x27       c28                            -1
    x27       c29                            -1
    x27       c30                            -1
    x27       c31                             1
    x27       c32                             1
    x27       c33                             1
    x27       c34                             1
    x27       c35                             1
    x27       c36                             1
    x27       c37                             1
    x28       c1                              1
    x28       c2                              1
    x28       c6                              1
    x28       c7                              1
    x28       c8                              1
    x28       c13                            -1
    x28       c14                            -1
    x28       c15                            -1
    x28       c19                             1
    x28       c20                             1
    x28       c21                             1
    x28       c31                            -1
    x28       c32                            -1
    x28       c33                            -1
    x28       c34                            -1
    x28       c35                            -1
    x28       c36                            -1
    x28       c37                            -1
    x29       c1                              1
    x29       c2                              1
    x29       c5                              1
    x29       c6                              1
    x29       c7                              1
    x29       c8                              1
    x29       c10                             1
    x29       c11                             1
    x29       c13                            -1
    x29       c14                            -1
    x29       c19                             1
    x29       c31                            -1
    x29       c33                            -1
    x30       c1                              1
    x30       c2                              1
    x30       c6                              1
    x30       c7                              1
    x30       c8                              1
    x30       c13                            -1
    x30       c14                            -1
    x30       c15                             1
    x30       c19                             1
    x30       c20                            -1
    x30       c21                            -1
    x30       c31                            -1
    x30       c32                             1
    x30       c33                            -1
    x30       c34                             1
    x30       c35                            -1
    x30       c36                             1
    x30       c37                            -1
    x31       c1                              1
    x31       c2                              1
    x31       c4                              1
    x31       c6                              1
    x31       c7                              1
    x31       c8                              1
    x31       c9                              1
    x31       c11                             1
    x31       c13                            -1
    x31       c15                            -1
    x31       c20                             1
    x31       c32                            -1
    x31       c35                            -1
    x32       c1                              1
    x32       c2                              1
    x32       c4                              1
    x32       c5                              1
    x32       c6                              1
    x32       c7                              1
    x32       c8                              1
    x32       c9                              1
    x32       c10                             1
    x32       c11                             1
    x32       c13                            -1
    x33       c1                              1
    x33       c2                              1
    x33       c4                              1
    x33       c6                              1
    x33       c7                              1
    x33       c8                              1
    x33       c9                              1
    x33       c11                             1
    x33       c13                            -1
    x33       c15                             1
    x33       c20                            -1
    x33       c32                             1
    x33       c35                            -1
    x34       c1                              1
    x34       c2                              1
    x34       c6                              1
    x34       c7                              1
    x34       c8                              1
    x34       c13                            -1
    x34       c14                             1
    x34       c15                            -1
    x34       c19                            -1
    x34       c20                             1
    x34       c21                            -1
    x34       c31                             1
    x34       c32                            -1
    x34       c33                            -1
    x34       c34                             1
    x34       c35                            -1
    x34       c36                            -1
    x34       c37                             1
    x35       c1                              1
    x35       c2                              1
    x35       c5                              1
    x35       c6                              1
    x35       c7                              1
    x35       c8                              1
    x35       c10                             1
    x35       c11                             1
    x35       c13                            -1
    x35       c14                             1
    x35       c19                            -1
    x35       c31                             1
    x35       c33                            -1
    x36       c1                              1
    x36       c2                              1
    x36       c6                              1
    x36       c7                              1
    x36       c8                              1
    x36       c13                            -1
    x36       c14                             1
    x36       c15                             1
    x36       c19                            -1
    x36       c20                            -1
    x36       c21                             1
    x36       c31                             1
    x36       c32                             1
    x36       c33                            -1
    x36       c34                            -1
    x36       c35                            -1
    x36       c36                             1
    x36       c37                             1
    x37       c1                              1
    x37       c2                              1
    x37       c3                              1
    x37       c6                              1
    x37       c7                              1
    x37       c8                              1
    x37       c9                              1
    x37       c10                             1
    x37       c14                            -1
    x37       c15                            -1
    x37       c21                             1
    x37       c36                            -1
    x37       c37                            -1
    x38       c1                              1
    x38       c2                              1
    x38       c3                              1
    x38       c5                              1
    x38       c6                              1
    x38       c7                              1
    x38       c8                              1
    x38       c9                              1
    x38       c10                             1
    x38       c11                             1
    x38       c14                            -1
    x39       c1                              1
    x39       c2                              1
    x39       c3                              1
    x39       c6                              1
    x39       c7                              1
    x39       c8                              1
    x39       c9                              1
    x39       c10                             1
    x39       c14                            -1
    x39       c15                             1
    x39       c21                            -1
    x39       c36                             1
    x39       c37                            -1
    x40       c1                              1
    x40       c2                              1
    x40       c3                              1
    x40       c4                              1
    x40       c6                              1
    x40       c7                              1
    x40       c8                              1
    x40       c9                              1
    x40       c10                             1
    x40       c11                             1
    x40       c15                            -1
    x41       c1                              1
    x41       c2                              1
    x41       c3                              1
    x41       c4                              1
    x41       c6                              1
    x41       c7                              1
    x41       c8                              1
    x41       c9                              1
    x41       c10                             1
    x41       c11                             1
    x41       c15                             1
    x42       c1                              1
    x42       c2                              1
    x42       c3                              1
    x42       c6                              1
    x42       c7                              1
    x42       c8                              1
    x42       c9                              1
    x42       c10                             1
    x42       c14                             1
    x42       c15                            -1
    x42       c21                            -1
    x42       c36                            -1
    x42       c37                             1
    x43       c1                              1
    x43       c2                              1
    x43       c3                              1
    x43       c5                              1
    x43       c6                              1
    x43       c7                              1
    x43       c8                              1
    x43       c9                              1
    x43       c10                             1
    x43       c11                             1
    x43       c14                             1
    x44       c1                              1
    x44       c2                              1
    x44       c3                              1
    x44       c6                              1
    x44       c7                              1
    x44       c8                              1
    x44       c9                              1
    x44       c10                             1
    x44       c14                             1
    x44       c15                             1
    x44       c21                             1
    x44       c36                             1
    x44       c37                             1
    x45       c1                              1
    x45       c2                              1
    x45       c6                              1
    x45       c7                              1
    x45       c8                              1
    x45       c13                             1
    x45       c14                            -1
    x45       c15                            -1
    x45       c19                            -1
    x45       c20                            -1
    x45       c21                             1
    x45       c31                            -1
    x45       c32                            -1
    x45       c33                             1
    x45       c34                             1
    x45       c35                             1
    x45       c36                            -1
    x45       c37                            -1
    x46       c1                              1
    x46       c2                              1
    x46       c5                              1
    x46       c6                              1
    x46       c7                              1
    x46       c8                              1
    x46       c10                             1
    x46       c11                             1
    x46       c13                             1
    x46       c14                            -1
    x46       c19                            -1
    x46       c31                            -1
    x46       c33                             1
    x47       c1                              1
    x47       c2                              1
    x47       c6                              1
    x47       c7                              1
    x47       c8                              1
    x47       c13                             1
    x47       c14                            -1
    x47       c15                             1
    x47       c19                            -1
    x47       c20                             1
    x47       c21                            -1
    x47       c31                            -1
    x47       c32                             1
    x47       c33                             1
    x47       c34                            -1
    x47       c35                             1
    x47       c36                             1
    x47       c37                            -1
    x48       c1                              1
    x48       c2                              1
    x48       c4                              1
    x48       c6                              1
    x48       c7                              1
    x48       c8                              1
    x48       c9                              1
    x48       c11                             1
    x48       c13                             1
    x48       c15                            -1
    x48       c20                            -1
    x48       c32                            -1
    x48       c35                             1
    x49       c1                              1
    x49       c2                              1
    x49       c4                              1
    x49       c5                              1
    x49       c6                              1
    x49       c7                              1
    x49       c8                              1
    x49       c9                              1
    x49       c10                             1
    x49       c11                             1
    x49       c13                             1
    x50       c1                              1
    x50       c2                              1
    x50       c4                              1
    x50       c6                              1
    x50       c7                              1
    x50       c8                              1
    x50       c9                              1
    x50       c11                             1
    x50       c13                             1
    x50       c15                             1
    x50       c20                             1
    x50       c32                             1
    x50       c35                             1
    x51       c1                              1
    x51       c2                              1
    x51       c6                              1
    x51       c7                              1
    x51       c8                              1
    x51       c13                             1
    x51       c14                             1
    x51       c15                            -1
    x51       c19                             1
    x51       c20                            -1
    x51       c21                            -1
    x51       c31                             1
    x51       c32                            -1
    x51       c33                             1
    x51       c34                            -1
    x51       c35                             1
    x51       c36                            -1
    x51       c37                             1
    x52       c1                              1
    x52       c2                              1
    x52       c5                              1
    x52       c6                              1
    x52       c7                              1
    x52       c8                              1
    x52       c10                             1
    x52       c11                             1
    x52       c13                             1
    x52       c14                             1
    x52       c19                             1
    x52       c31                             1
    x52       c33                             1
    x53       c1                              1
    x53       c2                              1
    x53       c6                              1
    x53       c7                              1
    x53       c8                              1
    x53       c13                             1
    x53       c14                             1
    x53       c15                             1
    x53       c19                             1
    x53       c20                             1
    x53       c21                             1
    x53       c31                             1
    x53       c32                             1
    x53       c33                             1
    x53       c34                             1
    x53       c35                             1
    x53       c36                             1
    x53       c37                             1
    x54       c1                              1
    x54       c12                             1
    x54       c13                            -1
    x54       c14                            -1
    x54       c15                            -1
    x54       c16                            -1
    x54       c17                            -1
    x54       c18                            -1
    x54       c19                             1
    x54       c20                             1
    x54       c21                             1
    x54       c22                            -1
    x54       c23                            -1
    x54       c24                            -1
    x54       c25                             1
    x54       c26                             1
    x54       c27                             1
    x54       c28                             1
    x54       c29                             1
    x54       c30                             1
    x54       c31                            -1
    x54       c32                            -1
    x54       c33                            -1
    x54       c34                            -1
    x54       c35                            -1
    x54       c36                            -1
    x54       c37                            -1
    x55       c1                              1
    x55       c5                              1
    x55       c8                              1
    x55       c10                             1
    x55       c11                             1
    x55       c12                             1
    x55       c13                            -1
    x55       c14                            -1
    x55       c16                            -1
    x55       c17                            -1
    x55       c19                             1
    x55       c22                            -1
    x55       c23                            -1
    x55       c25                             1
    x55       c26                             1
    x55       c28                             1
    x55       c31                            -1
    x55       c33                            -1
    x56       c1                              1
    x56       c12                             1
    x56       c13                            -1
    x56       c14                            -1
    x56       c15                             1
    x56       c16                            -1
    x56       c17                            -1
    x56       c18                             1
    x56       c19                             1
    x56       c20                            -1
    x56       c21                            -1
    x56       c22                            -1
    x56       c23                            -1
    x56       c24                             1
    x56       c25                             1
    x56       c26                             1
    x56       c27                            -1
    x56       c28                             1
    x56       c29                            -1
    x56       c30                             1
    x56       c31                            -1
    x56       c32                             1
    x56       c33                            -1
    x56       c34                             1
    x56       c35                            -1
    x56       c36                             1
    x56       c37                            -1
    x57       c1                              1
    x57       c4                              1
    x57       c7                              1
    x57       c9                              1
    x57       c11                             1
    x57       c12                             1
    x57       c13                            -1
    x57       c15                            -1
    x57       c16                            -1
    x57       c18                            -1
    x57       c20                             1
    x57       c22                            -1
    x57       c24                            -1
    x57       c25                             1
    x57       c27                             1
    x57       c30                             1
    x57       c32                            -1
    x57       c35                            -1
    x58       c1                              1
    x58       c4                              1
    x58       c5                              1
    x58       c7                              1
    x58       c8                              1
    x58       c9                              1
    x58       c10                             1
    x58       c11                             1
    x58       c12                             1
    x58       c13                            -1
    x58       c16                            -1
    x58       c22                            -1
    x58       c25                             1
    x59       c1                              1
    x59       c4                              1
    x59       c7                              1
    x59       c9                              1
    x59       c11                             1
    x59       c12                             1
    x59       c13                            -1
    x59       c15                             1
    x59       c16                            -1
    x59       c18                             1
    x59       c20                            -1
    x59       c22                            -1
    x59       c24                             1
    x59       c25                             1
    x59       c27                            -1
    x59       c30                             1
    x59       c32                             1
    x59       c35                            -1
    x60       c1                              1
    x60       c12                             1
    x60       c13                            -1
    x60       c14                             1
    x60       c15                            -1
    x60       c16                            -1
    x60       c17                             1
    x60       c18                            -1
    x60       c19                            -1
    x60       c20                             1
    x60       c21                            -1
    x60       c22                            -1
    x60       c23                             1
    x60       c24                            -1
    x60       c25                             1
    x60       c26                            -1
    x60       c27                             1
    x60       c28                             1
    x60       c29                            -1
    x60       c30                             1
    x60       c31                             1
    x60       c32                            -1
    x60       c33                            -1
    x60       c34                             1
    x60       c35                            -1
    x60       c36                            -1
    x60       c37                             1
    x61       c1                              1
    x61       c5                              1
    x61       c8                              1
    x61       c10                             1
    x61       c11                             1
    x61       c12                             1
    x61       c13                            -1
    x61       c14                             1
    x61       c16                            -1
    x61       c17                             1
    x61       c19                            -1
    x61       c22                            -1
    x61       c23                             1
    x61       c25                             1
    x61       c26                            -1
    x61       c28                             1
    x61       c31                             1
    x61       c33                            -1
    x62       c1                              1
    x62       c12                             1
    x62       c13                            -1
    x62       c14                             1
    x62       c15                             1
    x62       c16                            -1
    x62       c17                             1
    x62       c18                             1
    x62       c19                            -1
    x62       c20                            -1
    x62       c21                             1
    x62       c22                            -1
    x62       c23                             1
    x62       c24                             1
    x62       c25                             1
    x62       c26                            -1
    x62       c27                            -1
    x62       c28                             1
    x62       c29                             1
    x62       c30                             1
    x62       c31                             1
    x62       c32                             1
    x62       c33                            -1
    x62       c34                            -1
    x62       c35                            -1
    x62       c36                             1
    x62       c37                             1
    x63       c1                              1
    x63       c3                              1
    x63       c6                              1
    x63       c9                              1
    x63       c10                             1
    x63       c12                             1
    x63       c14                            -1
    x63       c15                            -1
    x63       c17                            -1
    x63       c18                            -1
    x63       c21                             1
    x63       c23                            -1
    x63       c24                            -1
    x63       c28                             1
    x63       c29                             1
    x63       c30                             1
    x63       c36                            -1
    x63       c37                            -1
    x64       c1                              1
    x64       c3                              1
    x64       c5                              1
    x64       c6                              1
    x64       c8                              1
    x64       c9                              1
    x64       c10                             1
    x64       c11                             1
    x64       c12                             1
    x64       c14                            -1
    x64       c17                            -1
    x64       c23                            -1
    x64       c28                             1
    x65       c1                              1
    x65       c3                              1
    x65       c6                              1
    x65       c9                              1
    x65       c10                             1
    x65       c12                             1
    x65       c14                            -1
    x65       c15                             1
    x65       c17                            -1
    x65       c18                             1
    x65       c21                            -1
    x65       c23                            -1
    x65       c24                             1
    x65       c28                             1
    x65       c29                            -1
    x65       c30                             1
    x65       c36                             1
    x65       c37                            -1
    x66       c1                              1
    x66       c3                              1
    x66       c4                              1
    x66       c6                              1
    x66       c7                              1
    x66       c9                              1
    x66       c10                             1
    x66       c11                             1
    x66       c12                             1
    x66       c15                            -1
    x66       c18                            -1
    x66       c24                            -1
    x66       c30                             1
    x67       c1                              1
    x67       c3                              1
    x67       c4                              1
    x67       c5                              1
    x67       c6                              1
    x67       c7                              1
    x67       c8                              1
    x67       c9                              1
    x67       c10                             1
    x67       c11                             1
    x67       c12                             1
    x68       c1                              1
    x68       c3                              1
    x68       c4                              1
    x68       c6                              1
    x68       c7                              1
    x68       c9                              1
    x68       c10                             1
    x68       c11                             1
    x68       c12                             1
    x68       c15                             1
    x68       c18                             1
    x68       c24                             1
    x68       c30                             1
    x69       c1                              1
    x69       c3                              1
    x69       c6                              1
    x69       c9                              1
    x69       c10                             1
    x69       c12                             1
    x69       c14                             1
    x69       c15                            -1
    x69       c17                             1
    x69       c18                            -1
    x69       c21                            -1
    x69       c23                             1
    x69       c24                            -1
    x69       c28                             1
    x69       c29                            -1
    x69       c30                             1
    x69       c36                            -1
    x69       c37                             1
    x70       c1                              1
    x70       c3                              1
    x70       c5                              1
    x70       c6                              1
    x70       c8                              1
    x70       c9                              1
    x70       c10                             1
    x70       c11                             1
    x70       c12                             1
    x70       c14                             1
    x70       c17                             1
    x70       c23                             1
    x70       c28                             1
    x71       c1                              1
    x71       c3                              1
    x71       c6                              1
    x71       c9                              1
    x71       c10                             1
    x71       c12                             1
    x71       c14                             1
    x71       c15                             1
    x71       c17                             1
    x71       c18                             1
    x71       c21                             1
    x71       c23                             1
    x71       c24                             1
    x71       c28                             1
    x71       c29                             1
    x71       c30                             1
    x71       c36                             1
    x71       c37                             1
    x72       c1                              1
    x72       c12                             1
    x72       c13                             1
    x72       c14                            -1
    x72       c15                            -1
    x72       c16                             1
    x72       c17                            -1
    x72       c18                            -1
    x72       c19                            -1
    x72       c20                            -1
    x72       c21                             1
    x72       c22                             1
    x72       c23                            -1
    x72       c24                            -1
    x72       c25                             1
    x72       c26                            -1
    x72       c27                            -1
    x72       c28                             1
    x72       c29                             1
    x72       c30                             1
    x72       c31                            -1
    x72       c32                            -1
    x72       c33                             1
    x72       c34                             1
    x72       c35                             1
    x72       c36                            -1
    x72       c37                            -1
    x73       c1                              1
    x73       c5                              1
    x73       c8                              1
    x73       c10                             1
    x73       c11                             1
    x73       c12                             1
    x73       c13                             1
    x73       c14                            -1
    x73       c16                             1
    x73       c17                            -1
    x73       c19                            -1
    x73       c22                             1
    x73       c23                            -1
    x73       c25                             1
    x73       c26                            -1
    x73       c28                             1
    x73       c31                            -1
    x73       c33                             1
    x74       c1                              1
    x74       c12                             1
    x74       c13                             1
    x74       c14                            -1
    x74       c15                             1
    x74       c16                             1
    x74       c17                            -1
    x74       c18                             1
    x74       c19                            -1
    x74       c20                             1
    x74       c21                            -1
    x74       c22                             1
    x74       c23                            -1
    x74       c24                             1
    x74       c25                             1
    x74       c26                            -1
    x74       c27                             1
    x74       c28                             1
    x74       c29                            -1
    x74       c30                             1
    x74       c31                            -1
    x74       c32                             1
    x74       c33                             1
    x74       c34                            -1
    x74       c35                             1
    x74       c36                             1
    x74       c37                            -1
    x75       c1                              1
    x75       c4                              1
    x75       c7                              1
    x75       c9                              1
    x75       c11                             1
    x75       c12                             1
    x75       c13                             1
    x75       c15                            -1
    x75       c16                             1
    x75       c18                            -1
    x75       c20                            -1
    x75       c22                             1
    x75       c24                            -1
    x75       c25                             1
    x75       c27                            -1
    x75       c30                             1
    x75       c32                            -1
    x75       c35                             1
    x76       c1                              1
    x76       c4                              1
    x76       c5                              1
    x76       c7                              1
    x76       c8                              1
    x76       c9                              1
    x76       c10                             1
    x76       c11                             1
    x76       c12                             1
    x76       c13                             1
    x76       c16                             1
    x76       c22                             1
    x76       c25                             1
    x77       c1                              1
    x77       c4                              1
    x77       c7                              1
    x77       c9                              1
    x77       c11                             1
    x77       c12                             1
    x77       c13                             1
    x77       c15                             1
    x77       c16                             1
    x77       c18                             1
    x77       c20                             1
    x77       c22                             1
    x77       c24                             1
    x77       c25                             1
    x77       c27                             1
    x77       c30                             1
    x77       c32                             1
    x77       c35                             1
    x78       c1                              1
    x78       c12                             1
    x78       c13                             1
    x78       c14                             1
    x78       c15                            -1
    x78       c16                             1
    x78       c17                             1
    x78       c18                            -1
    x78       c19                             1
    x78       c20                            -1
    x78       c21                            -1
    x78       c22                             1
    x78       c23                             1
    x78       c24                            -1
    x78       c25                             1
    x78       c26                             1
    x78       c27                            -1
    x78       c28                             1
    x78       c29                            -1
    x78       c30                             1
    x78       c31                             1
    x78       c32                            -1
    x78       c33                             1
    x78       c34                            -1
    x78       c35                             1
    x78       c36                            -1
    x78       c37                             1
    x79       c1                              1
    x79       c5                              1
    x79       c8                              1
    x79       c10                             1
    x79       c11                             1
    x79       c12                             1
    x79       c13                             1
    x79       c14                             1
    x79       c16                             1
    x79       c17                             1
    x79       c19                             1
    x79       c22                             1
    x79       c23                             1
    x79       c25                             1
    x79       c26                             1
    x79       c28                             1
    x79       c31                             1
    x79       c33                             1
    x80       c1                              1
    x80       c12                             1
    x80       c13                             1
    x80       c14                             1
    x80       c15                             1
    x80       c16                             1
    x80       c17                             1
    x80       c18                             1
    x80       c19                             1
    x80       c20                             1
    x80       c21                             1
    x80       c22                             1
    x80       c23                             1
    x80       c24                             1
    x80       c25                             1
    x80       c26                             1
    x80       c27                             1
    x80       c28                             1
    x80       c29                             1
    x80       c30                             1
    x80       c31                             1
    x80       c32                             1
    x80       c33                             1
    x80       c34                             1
    x80       c35                             1
    x80       c36                             1
    x80       c37                             1
    MARK0001  'MARKER'                 'INTEND'
RHS
    rhs       c1                             22
    rhs       c2                              6
    rhs       c3                              6
    rhs       c4                              6
    rhs       c5                              6
    rhs       c6                             10
    rhs       c7                             10
    rhs       c8                             10
    rhs       c9                             10
    rhs       c10                            10
    rhs       c11                            10
BOUNDS
 UP bnd       x1                              1
 UP bnd       x2                              1
 UP bnd       x3                              1
 UP bnd       x4                              1
 UP bnd       x5                              1
 UP bnd       x6                              1
 UP bnd       x7                              1
 UP bnd       x8                              1
 UP bnd       x9                              1
 UP bnd       x10                             1
 UP bnd       x11                             1
 UP bnd       x12                             1
 UP bnd       x13                             1
 UP bnd       x14                             1
 UP bnd       x15                             1
 UP bnd       x16                             1
 UP bnd       x17                             1
 UP bnd       x18                             1
 UP bnd       x19                             1
 UP bnd       x20                             1
 UP bnd       x21                             1
 UP bnd       x22                             1
 UP bnd       x23                             1
 UP bnd       x24                             1
 UP bnd       x25                             1
 UP bnd       x26                             1
 UP bnd       x27                             1
 UP bnd       x28                             1
 UP bnd       x29                             1
 UP bnd       x30                             1
 UP bnd       x31                             1
 UP bnd       x32                             1
 UP bnd       x33                             1
 UP bnd       x34                             1
 UP bnd       x35                             1
 UP bnd       x36                             1
 UP bnd       x37                             1
 UP bnd       x38                             1
 UP bnd       x39                             1
 UP bnd       x40                             1
 UP bnd       x41                             1
 UP bnd       x42                             1
 UP bnd       x43                             1
 UP bnd       x44                             1
 UP bnd       x45                             1
 UP bnd       x46                             1
 UP bnd       x47                             1
 UP bnd       x48                             1
 UP bnd       x49                             1
 UP bnd       x50                             1
 UP bnd       x51                             1
 UP bnd       x52                             1
 UP bnd       x53                             1
 UP bnd       x54                             1
 UP bnd       x55                             1
 UP bnd       x56                             1
 UP bnd       x57                             1
 UP bnd       x58                             1
 UP bnd       x59                             1
 UP bnd       x60                             1
 UP bnd       x61                             1
 UP bnd       x62                             1
 UP bnd       x63                             1
 UP bnd       x64                             1
 UP bnd       x65                             1
 UP bnd       x66                             1
 UP bnd       x67                             1
 UP bnd       x68                             1
 UP bnd       x69                             1
 UP bnd       x70                             1
 UP bnd       x71                             1
 UP bnd       x72                             1
 UP bnd       x73                             1
 UP bnd       x74                             1
 UP bnd       x75                             1
 UP bnd       x76                             1
 UP bnd       x77                             1
 UP bnd       x78                             1
 UP bnd       x79                             1
 UP bnd       x80                             1
ENDATA
